# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openmodel/v2/container.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1copenmodel/v2/container.proto\x12\x0copenmodel.v2\"\xfc\x01\n\x16OpenModelContainerInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12;\n\x06\x61uthor\x18\x03 \x01(\x0b\x32+.openmodel.v2.OpenModelContainerInfo.Author\x12\x41\n\tbiography\x18\x04 \x01(\x0b\x32..openmodel.v2.OpenModelContainerInfo.Biography\x1a%\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x1a\x1c\n\tBiography\x12\x0f\n\x07summary\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openmodel.v2.container_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OPENMODELCONTAINERINFO']._serialized_start=47
  _globals['_OPENMODELCONTAINERINFO']._serialized_end=299
  _globals['_OPENMODELCONTAINERINFO_AUTHOR']._serialized_start=232
  _globals['_OPENMODELCONTAINERINFO_AUTHOR']._serialized_end=269
  _globals['_OPENMODELCONTAINERINFO_BIOGRAPHY']._serialized_start=271
  _globals['_OPENMODELCONTAINERINFO_BIOGRAPHY']._serialized_end=299
# @@protoc_insertion_point(module_scope)
