# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openmodel/v2/drift.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18openmodel/v2/drift.proto\x12\x0copenmodel.v2\"9\n\nModelDrift\x12+\n\ndata_drift\x18\x01 \x01(\x0b\x32\x17.openmodel.v2.DataDrift\"\x1a\n\tDataDrift\x12\r\n\x05score\x18\x01 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openmodel.v2.drift_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODELDRIFT']._serialized_start=42
  _globals['_MODELDRIFT']._serialized_end=99
  _globals['_DATADRIFT']._serialized_start=101
  _globals['_DATADRIFT']._serialized_end=127
# @@protoc_insertion_point(module_scope)
