# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openmodel/v2/explanations.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openmodel.v2 import types_pb2 as openmodel_dot_v2_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fopenmodel/v2/explanations.proto\x12\x0copenmodel.v2\x1a\x18openmodel/v2/types.proto\"\xa9\x01\n\x0b\x45xplanation\x12+\n\x04none\x18\x03 \x01(\x0b\x32\x1b.openmodel.v2.NoExplanationH\x00\x12/\n\x05image\x18\x01 \x01(\x0b\x32\x1e.openmodel.v2.ImageExplanationH\x00\x12-\n\x04text\x18\x02 \x01(\x0b\x32\x1d.openmodel.v2.TextExplanationH\x00\x42\r\n\x0b\x65xplanation\"\x0f\n\rNoExplanation\"9\n\x10ImageExplanation\x12%\n\x04mask\x18\x01 \x01(\x0b\x32\x17.openmodel.v2.ImageMask\"\xfb\x01\n\x0fTextExplanation\x12\x41\n\rclass_results\x18\x01 \x03(\x0b\x32*.openmodel.v2.TextExplanation.ClassResults\x1aI\n\rTextSpanScore\x12)\n\ttext_span\x18\x01 \x01(\x0b\x32\x16.openmodel.v2.TextSpan\x12\r\n\x05score\x18\x02 \x01(\x01\x1aZ\n\x0c\x43lassResults\x12\r\n\x05\x63lass\x18\x01 \x01(\t\x12;\n\x06scores\x18\x02 \x03(\x0b\x32+.openmodel.v2.TextExplanation.TextSpanScoreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openmodel.v2.explanations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXPLANATION']._serialized_start=76
  _globals['_EXPLANATION']._serialized_end=245
  _globals['_NOEXPLANATION']._serialized_start=247
  _globals['_NOEXPLANATION']._serialized_end=262
  _globals['_IMAGEEXPLANATION']._serialized_start=264
  _globals['_IMAGEEXPLANATION']._serialized_end=321
  _globals['_TEXTEXPLANATION']._serialized_start=324
  _globals['_TEXTEXPLANATION']._serialized_end=575
  _globals['_TEXTEXPLANATION_TEXTSPANSCORE']._serialized_start=410
  _globals['_TEXTEXPLANATION_TEXTSPANSCORE']._serialized_end=483
  _globals['_TEXTEXPLANATION_CLASSRESULTS']._serialized_start=485
  _globals['_TEXTEXPLANATION_CLASSRESULTS']._serialized_end=575
# @@protoc_insertion_point(module_scope)
