# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openmodel/v2/types.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18openmodel/v2/types.proto\x12\x0copenmodel.v2\x1a\x1fgoogle/api/field_behavior.proto\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\"Z\n\x0b\x42oundingBox\x12\x0f\n\x01x\x18\x01 \x01(\x03\x42\x04\xe2\x41\x01\x02\x12\x0f\n\x01y\x18\x02 \x01(\x03\x42\x04\xe2\x41\x01\x02\x12\x13\n\x05width\x18\x03 \x01(\x03\x42\x04\xe2\x41\x01\x02\x12\x14\n\x06height\x18\x04 \x01(\x03\x42\x04\xe2\x41\x01\x02\"}\n\tImageMask\x12\x16\n\x0eoriginal_width\x18\x01 \x01(\x03\x12\x17\n\x0foriginal_height\x18\x02 \x01(\x03\x12\x0b\n\x03rle\x18\x03 \x03(\x03\x12\r\n\x05image\x18\x04 \x03(\x0c\x12#\n\x06points\x18\x05 \x03(\x0b\x32\x13.openmodel.v2.Point\"4\n\x08TextSpan\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\x12\x0c\n\x04text\x18\x03 \x01(\t\"\xe8\x02\n\x06Tensor\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\x30\n\tdata_type\x18\x02 \x01(\x0e\x32\x1d.openmodel.v2.Tensor.DataType\x12\x11\n\tbool_data\x18\x03 \x03(\x08\x12\x12\n\nint32_data\x18\x04 \x03(\x05\x12\x12\n\nint64_data\x18\x05 \x03(\x03\x12\x13\n\x0buint32_data\x18\x06 \x03(\r\x12\x13\n\x0buint64_data\x18\x07 \x03(\x04\x12\x14\n\x0c\x66loat32_data\x18\x08 \x03(\x02\x12\x14\n\x0c\x66loat64_data\x18\t \x03(\x01\x12\x10\n\x08raw_data\x18\n \x03(\x0c\"z\n\x08\x44\x61taType\x12\x1c\n\x18UNKNOWN_TENSOR_DATA_TYPE\x10\x00\x12\x08\n\x04\x42OOL\x10\x01\x12\t\n\x05INT32\x10\x02\x12\t\n\x05INT64\x10\x03\x12\n\n\x06UINT32\x10\x04\x12\n\n\x06UINT64\x10\x05\x12\x0b\n\x07\x46LOAT32\x10\x06\x12\x0b\n\x07\x46LOAT64\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openmodel.v2.types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOUNDINGBOX'].fields_by_name['x']._options = None
  _globals['_BOUNDINGBOX'].fields_by_name['x']._serialized_options = b'\342A\001\002'
  _globals['_BOUNDINGBOX'].fields_by_name['y']._options = None
  _globals['_BOUNDINGBOX'].fields_by_name['y']._serialized_options = b'\342A\001\002'
  _globals['_BOUNDINGBOX'].fields_by_name['width']._options = None
  _globals['_BOUNDINGBOX'].fields_by_name['width']._serialized_options = b'\342A\001\002'
  _globals['_BOUNDINGBOX'].fields_by_name['height']._options = None
  _globals['_BOUNDINGBOX'].fields_by_name['height']._serialized_options = b'\342A\001\002'
  _globals['_POINT']._serialized_start=75
  _globals['_POINT']._serialized_end=104
  _globals['_BOUNDINGBOX']._serialized_start=106
  _globals['_BOUNDINGBOX']._serialized_end=196
  _globals['_IMAGEMASK']._serialized_start=198
  _globals['_IMAGEMASK']._serialized_end=323
  _globals['_TEXTSPAN']._serialized_start=325
  _globals['_TEXTSPAN']._serialized_end=377
  _globals['_TENSOR']._serialized_start=380
  _globals['_TENSOR']._serialized_end=740
  _globals['_TENSOR_DATATYPE']._serialized_start=618
  _globals['_TENSOR_DATATYPE']._serialized_end=740
# @@protoc_insertion_point(module_scope)
