[project]
name = "chassisml-protobuf"
version = "3.0.0"
dependencies = [
    "protobuf >= 3.20.0, < 4",
    "grpclib",
]

[tool.setuptools.packages]
find = {}

[tool.setuptools.packages.find]
where = ["src"]
