cp -r /bin /kaniko
cp -r /boot /kaniko
cp -r /dev /kaniko
cp -r /etc /kaniko
cp -r /home /kaniko
cp -r /lib /kaniko
cp -r /lib64 /kaniko
cp -r /local /kaniko
cp -r /media /kaniko
cp -r /mnt /kaniko
cp -r /opt /kaniko
cp -r /root /kaniko
cp -r /run /kaniko
cp -r /sbin /kaniko
cp -r /srv /kaniko
cp -r /tmp /kaniko
cp -r /usr /kaniko
cp -r /var /kaniko
cp -r /workspace /kaniko