cp -rf /bin /kaniko
cp -rf /boot /kaniko
cp -rf /dev /kaniko
cp -rf /etc /kaniko
cp -rf /home /kaniko
cp -rf /lib /kaniko
cp -rf /lib64 /kaniko
cp -rf /local /kaniko
cp -rf /media /kaniko
cp -rf /mnt /kaniko
cp -rf /opt /kaniko
cp -rf /root /kaniko
cp -rf /run /kaniko
cp -rf /sbin /kaniko
cp -rf /srv /kaniko
cp -rf /tmp /kaniko
cp -rf /usr /kaniko
cp -rf /var /kaniko
cp -rf /workspace /kaniko
