[project]
name = "chassisml-omi-server"
version = "2.0.0"
dependencies = [
    "chassisml-protobuf"
]

#[tool.setuptools.packages]
#find = {}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.pyi"]