# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from .....grpc_model.src.auto_generated.model2_template import model_pb2 as model2__template_dot_model__pb2


class ModzyModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
            "/ModzyModel/Status",
            request_serializer=model2__template_dot_model__pb2.StatusRequest.SerializeToString,
            response_deserializer=model2__template_dot_model__pb2.StatusResponse.FromString,
        )
        self.Run = channel.unary_unary(
            "/ModzyModel/Run",
            request_serializer=model2__template_dot_model__pb2.RunRequest.SerializeToString,
            response_deserializer=model2__template_dot_model__pb2.RunResponse.FromString,
        )
        self.Shutdown = channel.unary_unary(
            "/ModzyModel/Shutdown",
            request_serializer=model2__template_dot_model__pb2.ShutdownRequest.SerializeToString,
            response_deserializer=model2__template_dot_model__pb2.ShutdownResponse.FromString,
        )


class ModzyModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ModzyModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Status": grpc.unary_unary_rpc_method_handler(
            servicer.Status,
            request_deserializer=model2__template_dot_model__pb2.StatusRequest.FromString,
            response_serializer=model2__template_dot_model__pb2.StatusResponse.SerializeToString,
        ),
        "Run": grpc.unary_unary_rpc_method_handler(
            servicer.Run,
            request_deserializer=model2__template_dot_model__pb2.RunRequest.FromString,
            response_serializer=model2__template_dot_model__pb2.RunResponse.SerializeToString,
        ),
        "Shutdown": grpc.unary_unary_rpc_method_handler(
            servicer.Shutdown,
            request_deserializer=model2__template_dot_model__pb2.ShutdownRequest.FromString,
            response_serializer=model2__template_dot_model__pb2.ShutdownResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("ModzyModel", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ModzyModel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Status(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ModzyModel/Status",
            model2__template_dot_model__pb2.StatusRequest.SerializeToString,
            model2__template_dot_model__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Run(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ModzyModel/Run",
            model2__template_dot_model__pb2.RunRequest.SerializeToString,
            model2__template_dot_model__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Shutdown(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ModzyModel/Shutdown",
            model2__template_dot_model__pb2.ShutdownRequest.SerializeToString,
            model2__template_dot_model__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
