apiVersion: batch/v1
kind: Job
metadata:
  name: "{{JOB_NAME}}"
  labels:
    chassisml.io/job-identifier: "{{JOB_IDENTIFIER}}"
  annotations:
    chassisml.io/destination: "{{IMAGE_NAME}}"
spec:
  backoffLimit: 0
  activeDeadlineSeconds: {{TIMEOUT}}
  ttlSecondsAfterFinished: {{TTL_AFTER_FINISHED}}
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: prepare
          image: alpine:3.10
          command:
            - sh
            - -c
            - |-
              wget {{CONTEXT_URL}} && \
              unzip -d /workspace context.zip && \
              rm context.zip
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      containers:
        - name: buildkit
          image: moby/buildkit:latest
          command:
            - buildctl-daemonless.sh
          args:
            - build
            - --frontend
            - dockerfile.v0
            - --opt
            - platform={{PLATFORM}}
            - --local
            - context=/workspace
            - --local
            - dockerfile=/workspace
            - --output
            - type=image,name={{IMAGE_NAME}},push=true{{{ADDTL_OPTIONS}}}
          resources: {{{RESOURCES}}}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /workspace
              name: workspace
{{#if CREDS}}
            - mountPath: /root/.docker
              name: creds
{{/if}}
      volumes:
        - name: workspace
          emptyDir: {}
{{#if CREDS}}
        - name: creds
          secret:
            secretName: {{CREDS}}
{{/if}}