# Default values for chassis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This values are populated from the service .env file.
#SERVICE_REPOSITORY: 'saumild13/gcp-chassis:0.0.17'
SERVICE_REPOSITORY: 'claytondavisms/chassis-proxy:0.0.2'

PORT: "5000"
MOUNT_PATH_DIR: "/data"
WORKSPACE_DIR: "workspace"
K_ENVIRONMENT: "default"
K_JOB_NAME: "chassis-builder-job"
K_DATA_VOLUME_NAME: "kaniko-data"
K_EMPTY_DIR_NAME: "registry-credentials"
K_INIT_EMPTY_DIR_PATH: "/tmp/credentials"
K_KANIKO_EMPTY_DIR_PATH: "/kaniko/.docker"
K_SERVICE_ACCOUNT_NAME: "job-builder"

MODE: "s3"
CONTEXT_BUCKET: "chassis-contexts"
CREDENTIALS_FILEPATH: "secrets/credentials"

HTTP_PROXY: "http://10.10.4.109:3128"
HTTPS_PROXY: "http://10.10.4.109:3128"
NO_PROXY: "modzy.engineering,10.0.0.0/8"

#HTTP_PROXY: ""
#HTTPS_PROXY: ""
#NO_PROXY: ""

replicaCount: 1

image:
  repository: ghcr.io/modzy/chassis-service
  # tag: 0.0.1
  pullPolicy: Always
  # IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: "chassis"
fullnameOverride: "chassis"

env:
  - name: foo
    value: bar


rbac:
  # Specifies whether RBAC resources should be created
  create: false

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use is used from above K_SERVICE_ACCOUNT_NAME value.

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: modzy-kqgqi.modzy.engineering
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chassis
                port:
                  number: 5000
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

restartPolicy: OnFailure
