[project]
name = "chassisml"
version = "1.5.0"
authors = [
    { name="Bradley Munday", email="bradley.munday@modzy.com" },
    { name="Nathan Mellis", email="nathan.mellis@modzy.com" },
    { name="Carlos Millán Soler", email="cmillan@sciling.com" },
]
description = ""
readme = "README.md"
requires-python = ">= 3.8"
classifiers = [
]
license = { file = "LICENSE" }
dependencies = [
    "requests",
    "packaging",
    "chassisml-protobuf",
    "Jinja2 >= 3.1.2",
    "cloudpickle == 2.2.0",
    "pyyaml",
    "docker",
    "validators",
    "numpy",
    "pip-tools",
]

[project.optional-dependencies]
test = ["pytest"]
kserve = ["kserve >= 0.11"]
quickstart = ["scikit-learn"]
docs = [
    "mkdocs>=1.3.0",
    "mkdocs-autorefs>=0.4.1",
    "mkdocs-material>=8.1.6",
    "mkdocs-material-extensions>=1.0.3",
    "mkdocs-minify-plugin>=0.6.2",
    "mkdocstrings[python]>=0.18",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
]

[project.urls]
"Homepage" = "https://modzy.github.io/chassis"
"Repository" = "https://github.com/modzy/chassis"
"Bug Tracker" = "https://github.com/modzy/chassis/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.pyi"]
"chassis.builder" = ["templates/*"]
"chassis.guides" = ["data/*"]

[build-system]
requires = ["setuptools>=41.0.0"]
build-backend = "setuptools.build_meta"