[project]
name = "chassisml"
version = "1.5.0"
authors = [
    { name="Bradley Munday", email="bradley.munday@modzy.com" },
    { name="Nathan Mellis", email="nathan.mellis@modzy.com" },
    { name="Carlos Millán Soler", email="cmillan@sciling.com" },
]
description = ""
readme = "README.md"
requires-python = ">= 3.9"
classifiers = [
]
license = { file = "LICENSE" }
dependencies = [
    "requests",
    "packaging",
    "chassisml-protobuf",
    "Jinja2 >= 3.1.2",
    "cloudpickle == 2.2.0",
    "pyyaml",
    "docker",
]
optional-dependencies = [
    "pytest",
]

[project.urls]
"Homepage" = "https://modzy.github.io/chassis"
"Repository" = "https://github.com/modzy/chassis"
"Bug Tracker" = "https://github.com/modzy/chassis/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.pyi"]
"chassis.packager" = ["templates/*"]

[build-system]
requires = ["setuptools>=41.0.0"]
build-backend = "setuptools.build_meta"