# project info
site_name: Chassis

# repository
repo_url: https://github.com/modzy/chassis
repo_name: modzy/chassis
edit_uri: edit/main/docs/docs/

# copyright
copyright: Copyright &copy; 2023 Modzy

# config
theme:
  name: material
  custom_dir: material/overrides
  palette:
    scheme: chassis
  logo: images/chassis-symbol-negative.png
  favicon: images/chassis-symbol.png
  features:
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.header
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

# plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true      
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys 
            - sys.path.append('../')
            - sys.path.append('../packages/chassisml/src/')
          selection:
            new_path_syntax: true
            docstring_style: "google" 
          rendering:
            show_category_heading: no

# customization
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-4NVL0DTGZ4
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/eW4kHSm3Z5
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/chassisml/
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/mlops-community/shared_invite/zt-10jopsclv-sny902l2GOFdElU2blfACg
    - icon: fontawesome/brands/github
      link: https://github.com/modzy/chassis

# extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true    
  - pymdownx.tasklist:
      custom_checkbox: true      

nav:
  - Home: index.md
  - Getting Started: getting-started/getting-started.md
  - Tutorials: 
      - tutorials/index.md
      - Install Remote Service: tutorials/install-service.md
  - How-to Guides:
      - how-to-guides/index.md
      - Model Containers by Framework: how-to-guides/frameworks.md
      - Common Data Types Support: how-to-guides/common-data-types.md
  - Reference:
      - reference/index.md
      - Chassisml Service: reference/service.md
      - Python SDK: reference/sdk.md
      - Interfaces:
          - OMI: reference/omi.md
          - KServe: reference/kserve.md
  - Community:
      - Get Involved: community/get-involved.md
  - Release Notes: release-notes.md
