# project info
site_name: Chassis

# repository
repo_url: https://github.com/modzy/chassis
repo_name: modzy/chassis
edit_uri: edit/main/docs/docs/

# copyright
copyright: Copyright &copy; 2023 Modzy

# config
theme:
  name: material
  custom_dir: material/overrides
  palette:
    scheme: chassis
  logo: images/chassis-symbol-negative.png
  favicon: images/chassis-symbol.png
  features:
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.header
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

# plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - gen-files:
      scripts:
        - docs/generate_sdk_pages.py
  - literate-nav:
      nav_file: navigation.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["../packages/chassisml/src"]
          options:
            allow_inspection: false
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            docstring_style: "google"
            filters:
              - "!^_"
            group_by_category: true
            heading_level: 3
            inherited_members: true
            line_length: 60
            members_order: source
            merge_init_into_class: true            
            preload_modules:
              - chassis
            separate_signature: true
            show_bases: false
            show_category_heading: false
            show_if_no_docstring: true
            show_object_full_path: false
            show_root_full_path: false
            show_root_heading: false
            show_root_members_full_path: false
            show_root_toc_entry: false
            show_signature: true
            show_signature_annotations: false
            show_source: false
            show_submodules: false


watch:
  - ../packages/chassisml/src/chassis
  - ../packages/chassisml/src/chassisml

# customization
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-4NVL0DTGZ4
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/eW4kHSm3Z5
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/chassisml/
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/mlops-community/shared_invite/zt-10jopsclv-sny902l2GOFdElU2blfACg
    - icon: fontawesome/brands/github
      link: https://github.com/modzy/chassis

# extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true    
  - pymdownx.tasklist:
      custom_checkbox: true      

nav:
  - Home: index.md
  - Getting Started: 
      - getting-started/index.md
      - Quickstart: getting-started/quickstart.md
      - Full Chassis Workflow: getting-started/full-workflow.md
  - Guides:
      # - guides/index.md
      - Common ML/DL Frameworks: 
          - guides/frameworks/index.md
          - Diffusers: guides/frameworks/diffusers.md
          - Torch: guides/frameworks/torch.md
          - Transformers: guides/frameworks/transformers.md
      - Common Data Bytes Conversion: guides/common-data-types.md
      - Install Remote Service: guides/install-service.md
  - Reference:
      - Chassis Basics: reference/basics.md
      - Interfaces: reference/interfaces.md
      - Chassis SDK: reference/sdk/
  - Get Involved:
      - get-involved/index.md
  - Release Notes: release-notes.md
