# project info
site_name: Chassis

# repository
repo_url: https://github.com/modzy/chassis
repo_name: modzy/chassis
edit_uri: edit/main/docs/docs/

# copyright
copyright: Copyright &copy; 2023 Modzy

# config
theme:
  name: material
  custom_dir: material/overrides
  palette:
    scheme: chassis
  logo: images/chassis-symbol-negative.png
  favicon: images/chassis-symbol.png
  features:
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.header
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

# plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - gen-files:
      scripts:
        - docs/generate_sdk_pages.py
  - literate-nav:
      nav_file: navigation.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["../packages/chassisml/src"]
          options:
            docstring_style: "google"
            docstring_section_style: list
            show_if_no_docstring: true
            preload_modules:
              - chassis
            show_source: false
            heading_level: 3
            show_root_toc_entry: false
            show_category_heading: false
            inherited_members: true
            show_signature: true
            show_signature_annotations: true
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: false
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true


watch:
  - ../packages/chassisml/src/chassis
  - ../packages/chassisml/src/chassisml

# customization
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-4NVL0DTGZ4
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/eW4kHSm3Z5
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/chassisml/
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/mlops-community/shared_invite/zt-10jopsclv-sny902l2GOFdElU2blfACg
    - icon: fontawesome/brands/github
      link: https://github.com/modzy/chassis

# extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true    
  - pymdownx.tasklist:
      custom_checkbox: true      

nav:
  - Home: index.md
  - Getting Started: 
      - getting-started/index.md
      - Quickstart: getting-started/quickstart.md
      - Full Chassis Workflow: getting-started/full-workflow.md
  - Tutorials: 
      - tutorials/index.md
      - Install Remote Service: tutorials/install-service.md
  - How-to Guides:
      - how-to-guides/index.md
      - Model Containers by Framework: how-to-guides/frameworks.md
      - Common Data Types Support: how-to-guides/common-data-types.md
  - Reference:
      - reference/index.md
      - Chassis SDK: reference/sdk/
  - Community:
      - Get Involved: community/get-involved.md
  - Release Notes: release-notes.md
