site_name: Chassis
nav:
  - index.md
  # - landing/connect.md
  # - connect.md
  # - Home:
  #     - connect.md
  #     - index.md
  - Getting Started:
      - Installation:
          - getting-started/deploy-connect.md
          - getting-started/deploy-manual.md
  - Tutorials:
      - tutorials/ds-connect.md
      - tutorials/ds-postman.md
      - tutorials/ds-deploy.md
      - tutorials/ds-deploy-modzy.md
  - How-to Guides:
      - Model Containers by Framework: how-to-guides/frameworks.md
      - Arm Support: how-to-guides/arm-support.md
      - GPU Support: how-to-guides/gpu-support.md
      # - Adding Explainability: how-to-guides/explainability.md
  - Reference:
      - Chassisml Service: service-reference.md
      - Python SDK: chassisml_sdk-reference.md
  - Conceptual Guides:
      - Overview: conceptual-guides/overview.md
      - Design & Architecture: conceptual-guides/design.md
      - gRPC: conceptual-guides/grpc.md
      - Containers: conceptual-guides/containers.md
  - Get Involved: get-involved.md
  - Release Notes: release-notes.md
theme:
  name: material
  palette:
    scheme: chassis
  logo: images/chassis-symbol-negative.png
  favicon: images/chassis-symbol.png
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - toc.integrate
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys 
            - sys.path.append('../')
            - sys.path.append('../service/')
          selection:
            new_path_syntax: true
            docstring_style: "google" 
          rendering:
            show_category_heading: no
markdown_extensions:
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
repo_url: https://github.com/modzy/chassis
repo_name: modzy/chassis
edit_uri: edit/main/docs/docs/
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-4NVL0DTGZ4
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Fk5sUfZPGE
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/chassisml/
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/mlops-community/shared_invite/zt-10jopsclv-sny902l2GOFdElU2blfACg
    - icon: fontawesome/brands/github
      link: https://github.com/modzy/chassis
copyright: Copyright &copy; 2022 Modzy
# use_directory_controls: false
