name: CI_PR

# Controls when the action will run.
on:
  pull_request:
    branches:
      - main
      - release-v*

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lint:
    name: Run Python lint and type checks
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: 3.9
          cache: pip
          cache-dependency-path: |
            packages/chassisml/pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./packages/chassisml[test]

      - name: Lint
        run: tox -e lint

  #      - name: Verify Types
  #        run: tox -e type

  tests:
    name: Run tests for ${{ matrix.os }}/${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        include:
          - python-version: "3.8"
            tox-name: py38
          - python-version: "3.9"
            tox-name: py39
          - python-version: "3.10"
            tox-name: py310
          - python-version: "3.11"
            tox-name: py311
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          cache: pip
          cache-dependency-path: |
            packages/chassisml/pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./packages/chassisml[test]

      - name: Run tests
        run: |
          tox -e ${{ matrix.tox-name }}

  pip:
    name: Build SDK
    needs: [lint, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: |
            packages/chassisml/pyproject.toml

      - name: Install pypa/build
        run: |
          pip install build

      - name: Build distribution
        run: |
          python3 -m build --sdist --wheel --outdir dist/ packages/chassisml
